### ISSUE TITLE
Did you try a "back channel"?

### ISSUE THREAD

**Issue by SensorsIot** [leonyuhanov/ESP-NOW-TX-RX#1]
The communication from the transmitter to the receiver works for me. But I need also a communication in the other direction. Were you able to do that?

**Comment by leonyuhanov** [comment]
I have not tried yet :) But i will test tonight and post up some code!

**Comment by leonyuhanov** [comment]
Hey Andreas have a look inside the 2 new directories https://github.com/leonyuhanov/ESP-NOW-TX-RX/tree/master/DualModeMaster and https://github.com/leonyuhanov/ESP-NOW-TX-RX/tree/master/DualModeSlave 
I tested this on 2 x WemosD1 Mini ESP8266 modules and it works perfectly. You have to add both devices as "ESP_NOW_ROLE_CONTROLLER" respectively. Let me know how you go?
PS: I love your YT channel!
