### ISSUE TITLE
DUAL Mode RX/TX for ESP32?

### ISSUE THREAD

**Issue by thomasfla** [leonyuhanov/ESP-NOW-TX-RX#2]
Hi, Thanks for sharing here your clear examples.

I would like to use ESPNOW for a closed-loop robotic project with two ESP32s in the loop. 
It looks like your example of DUAL Mode RX/TX is the perfect starting point. However it only applies to ESP8266. Do you have some tips to adapt this example to ESP32? for example, I believe there is no such ESP_NOW_ROLE_CONTROLLER in the ESP32 API?

Also do you have some results in mind for the loop-back time you get with the ESP8266s?

Ideally I would like to get a 1ms control cycle, with a payload < 100 bytes, but I'm starting to think ESP is may not capable of doing that...

**Comment by leonyuhanov** [comment]
Hey @thomasfla Please do not open ISSUES when what you want is help/feature request. Converting this to ESP32 is trivial, please look at the esp32 examples and DIY :) FYI the round trip length is in the MICROSECONDS range and will definitely work for what you want to do.

**Comment by thomasfla** [comment]
Thanks @leonyuhanov, sorry for the issue..
 No problem I will adapt it myself. Are you interesting in a pull request from me as soon as I have it working? 

By the way, I did some measurement with a scope and two ESP32, each triggering a pin at sending and receiving, with your examples **ESP32_Transmiter**.ino and **ESP32_Receiver**.ino (so just one way). The results are a bit disappointing:

> Payload of 32 bytes -> **1.06 ms** (719 kbit/s)
> Payload of 250 bytes -> **2.78 ms** (256 kbit/s)

I guess I should expect at least double for a round trip length.. May be this is only a problem with the ESP32 API? I will investigate all this..

**Comment by leonyuhanov** [comment]
i think your timing results are way off. payload length via the espnow protocol is irelivent. it always sends the same data packet length. and a rouns trip is somewhere in the MicroSecond length UNDER 1 milisecond. i sugest reviewing the code and your test. keep me posted happy to help

**Comment by thomasfla** [comment]
Hum, I've checked my code and measurements today, I think everything is ok..
I agree, the payload should have no effect on the effective size of the packet witch is fixed by vendor-specific action frame, but yet, somehow, it does affect the transmission time...
Here is the modified code to trigger a pin when receiving or sending..

### Receiver's code
```
#include <esp_now.h>
#include <WiFi.h>

#define WIFI_CHANNEL 1
uint8_t localCustomMac[] = {0x36, 0x33, 0x33, 0x33, 0x33, 0x33};
const byte maxDataFrameSize = 32;
byte cnt=0;

int LED_BUILTIN = 2;

void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(115200);
  esp_base_mac_addr_set(localCustomMac);
  WiFi.mode(WIFI_AP_STA); 
  esp_now_init();
  delay(10);
  
  esp_now_register_recv_cb(OnDataRecv);
}

void loop()
{
 
}

void OnDataRecv(const uint8_t *mac_addr, const uint8_t *data, int data_len)
{
  digitalWrite(LED_BUILTIN, HIGH);
  Serial.println(data[0], DEC);
  digitalWrite(LED_BUILTIN, LOW);
}
```



### Transmitter's code
```
#include <esp_now.h>
#include <WiFi.h>

#define WIFI_CHANNEL 1
esp_now_peer_info_t slave;
uint8_t remoteMac[] = {0x36, 0x33, 0x33, 0x33, 0x33, 0x33};
const uint8_t maxDataFrameSize=32;
const esp_now_peer_info_t *peer = &slave;
uint8_t dataToSend[maxDataFrameSize];
byte cnt=0;

int LED_BUILTIN = 2;

void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(115200);
  WiFi.disconnect();
  WiFi.mode(WIFI_STA);
  esp_now_init();
  delay(10);
  memcpy( &slave.peer_addr, &remoteMac, 6 );
  slave.channel = WIFI_CHANNEL;
  slave.encrypt = 0;
  esp_now_add_peer(peer);
}

void loop()
{
  for(cnt=0; cnt<maxDataFrameSize; cnt++)
  {
    dataToSend[cnt]++;
  }
  digitalWrite(LED_BUILTIN, HIGH);
  esp_now_send(slave.peer_addr, dataToSend, maxDataFrameSize);
  digitalWrite(LED_BUILTIN, LOW);
  Serial.println(dataToSend[0], DEC);
  delay(10);
}
```
Here are the scope measurement when `maxDataFrameSize = 250`
![tek00001](https://user-images.githubusercontent.com/11156435/44977146-856ff780-af67-11e8-8ca1-32cfc335520e.png)

And when `maxDataFrameSize = 32`
![tek00002](https://user-images.githubusercontent.com/11156435/44977147-856ff780-af67-11e8-8493-fd301fdc2c99.png)

The large delay are still a mystery to me.. And I don't see any reason why it is payload size dependent.
Any clues? 

I'm planning to test similar setup with ESP8266 to reproduce your results.
Thanks again.

**Comment by leonyuhanov** [comment]
@thomasfla  Yeah its weird, on the esp8266 its miles faster! A full round trip takes under a milisecond
