### ISSUE TITLE
DualModeExamples do not work with ESP32

### ISSUE THREAD

**Issue by SensorsIot** [leonyuhanov/ESP-NOW-TX-RX#3]
I changed the ESP8266 example to: 
#include <WiFi.h>
#include <esp_now.h>

but it does not compile for the ESP32:
DualModeSlave:30: error: 'ESP_NOW_ROLE_CONTROLLER' was not declared in this scope
   esp_now_set_self_role(ESP_NOW_ROLE_CONTROLLER);
We ned it for the ESP32

**Comment by leonyuhanov** [comment]
I see ill upload a workimg esp32 exaple later today

**Comment by leonyuhanov** [comment]
Hey mate
I have updated both the ESP32 TX and RX examples and added dual mode for esp32! Its damn tricky but i got it working!

**Comment by SensorsIot** [comment]
Thank you for adding the examples. I entered the MAC addresses and started both nodes at the same time. 
On the Master I get:
24:0A:C4:0D:81:E0
ESP NOW INIT!
Added Peer!

and on the Slave:
24:0A:C4:0D:17:E9
ESPNow Init Success!
Added Master Node!

unfortunately then I get on the mater:
Success Sent Value->	1
Last Packet Send Status:	Delivery Fail
Success Sent Value->	2
Last Packet Send Status:	Delivery Fail
Success Sent Value->	3
Last Packet Send Status:	Delivery Fail
Success Sent Value->	4
Last Packet Send Status:	Delivery Fail

and on the slave nothing more
It seems that OnDataRecv() is not called

**Comment by leonyuhanov** [comment]
please carefully read the readme on this repo. I wrote special instructions for gwtting 2 way coms on the esp32. theres a few hoops to jump through

**Comment by SensorsIot** [comment]
I thought I did follow the instructions. I used your two sketches and replaced the addresses as follows:
Master:
uint8_t remoteMac[] = {0x24, 0x0A, 0xC4, 0x0D, 0x17, 0xE9};
Based on this output from the slave:
24:0A:C4:0D:17:E9
ESPNow Init Success!
Added Master Node!

Slave:
uint8_t masterDeviceMac[] = {0x24, 0x0A, 0xC4, 0x0D, 0x81, 0xE0};
Based on this output from master:
24:0A:C4:0D:81:E0
ESP NOW INIT!
Added Peer!
Line 38 is already there in your slave sketch

CHANNEL is on both sketches 1
What did I forget?

**Comment by leonyuhanov** [comment]
On The SLAVE node upload a blank sketch that lets you print the nodes WIFI_AP MAC address
via WiFi.softAPmacAddress(). This will be the SLAVE MAC
On the MASTER node upload a blank sketch that lets you print the nodes WIFI_STA MAC address via WiFi.macAddress(). This will be the MASTER MAC

Now using my examples:

In ESP32_DualMode_Slave.ino on line 10 
`uint8_t masterDeviceMac[]`
Set that to the MASTER MAC

in ESP32_DualMode_Master.ino on line 10
`uint8_t remoteMac[]`
Set that to the SLAVE MAC

That should work, its exactly what im doing.

**Comment by SensorsIot** [comment]
Now it works. Thank you!

**Comment by leonyuhanov** [comment]
Awesome, glad to help mate! Your YT Chanel is awesome, thanks for being awesome! I mostly do wotk with addressable LEDs here is my insta https://www.instagram.com/wow_elec_tron/ if you ever need any led stuff shoot me a wow!

**Comment by JL1946** [comment]
Unfortunately, the method you propose is ok for a one-of, but fails in practice if you have to use a blank sketch to get MAC addresses. I do it a bit different... knowing that Station Mode can be assigned a Custom MAC that will not be changed by the firmware (as it is in AP Mode) I assign custom MACs to each device and use STA Mode for both. This way, I know that the custom MAC will stick. You don't need AP Mode to look for a device when both devices ("Master" and "Slave") are in front of you.
Take a quick look at the modifications I made to your code: https://github.com/JL1946/Working-ESP_NOW-Master-Slave-STA-Mode/tree/master

**Comment by leonyuhanov** [comment]
> the method you propose is ok for a one-of

Correct that was my intention, thank you for linking your modified code.
