### ISSUE TITLE
You did a great job - thank you

### ISSUE THREAD

**Issue by StefanL38** [leonyuhanov/ESP-NOW-TX-RX#4]
Hello leonyuhanov,

I tried to find something  like a "private message" function. But I didn't find anything.
I googled for send a message to a github-user. the results only stated go to userpage and search for email. Did'nt find one. So as I'm even pretty new to Github itself I'm kind of misusing the issue-function for this "private message" If there is a private-message-function I would appreciate it very much to be guided there.

Anyway thank you very much for your ESP-NOW TX-RX-example-code and the additional readme-information below the codefiles.

Much better doumentated and explained than some other code-examples I was looking at.
If you have a link handy where I could read some more about the different configurations 
one master multiple-slaves.    one slave mutliple-masters (if possible) and which function master/slave/repeater is related to which WIfi-mode I would be very thankful.

best regards  

Stefan

**Comment by leonyuhanov** [comment]
Have a look at Espressifs docs here https://www.espressif.com/en/products/software/esp-now/overview
