### ISSUE TITLE
ESP32_DualMode_Slave fails on ESP32

### ISSUE THREAD

**Issue by yashmulgaonkar** [leonyuhanov/ESP-NOW-TX-RX#5]
Line https://github.com/leonyuhanov/ESP-NOW-TX-RX/blob/494a06e5a40242403cd51a3070f1d017be3c5080/ESP32_DualMode_Slave/ESP32_DualMode_Slave.ino#L37 causes a compile error:

The following error manifests on compiling:

```
error: cannot convert 'esp_interface_t' to 'wifi_interface_t' in assignment
   master.ifidx = ESP_IF_WIFI_AP;
                  ^~~~~~~~~~~~~~
```

**Comment by leonyuhanov** [comment]
can u post your code or at least the line of code the error is thrown at pls?

**Comment by yashmulgaonkar** [comment]
https://github.com/leonyuhanov/ESP-NOW-TX-RX/blob/494a06e5a40242403cd51a3070f1d017be3c5080/ESP32_DualMode_Slave/ESP32_DualMode_Slave.ino#L37

Found a hotfix: Change `ESP_IF_WIFI_AP` to `WIFI_IF_AP`

**Comment by leonyuhanov** [comment]
Thanks @yashm will fix the repo code now!
