### ISSUE TITLE
Read / poll RSSI values from Tx / Rx

### ISSUE THREAD

**Issue by yashmulgaonkar** [leonyuhanov/ESP-NOW-TX-RX#6]
Hello,
Is there a way to read RSSI values on the Tx / Rx without polling for all access points?

**Comment by leonyuhanov** [comment]
@yashm not sure, I would suggest looking through their SDK.

**Comment by TD-er** [comment]
Please double check whether your system still works fine regarding sending/receiving ESP-NOW packets when you frequently call the RSSI from your WiFi object.
The same applies for WiFi scanning.

You can however add an event callback when you're being scanned.
In this event, there is an RSSI value of the one scanning you.
This way you know the RSSI of the other node and typically the RSSI is in the same order of magnitude in both directions.

**Comment by leonyuhanov** [comment]
@TD-er this repo is a very simple get started guide for espnow,I havnt included anything to do with rssi in this.
