### ISSUE TITLE
Transmitter ino needs a valid WiFi SSID and Password to work

### ISSUE THREAD

**Issue by VinceW31** [leonyuhanov/ESP-NOW-TX-RX#7]
In your code for ESP8266 Transmitter.ino I cant get it to work at all with WiFi.begin(); it just hangs forever waiting for WiFi connection.
But if I enter a valid SSID and Password then ESPNow data is sent and received just fine.  On the ESP32 though this works ok with just WiFi.begin();

**Comment by leonyuhanov** [comment]
I have comented out that line, prob don't need it at all
